# Use custom format
#format = """
#[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green)
#[â”‚](bold green)$username$directory$rust$package
#[â””â”€>](bold green) """

# Don't print a new line at the start of the prompt
add_newline = true

[username]
format = '\[[$user]($style)\]'

[cmd_duration]
disabled = true

[line_break]
disabled = true

[package]
disabled = true

[directory]
style = "bold cyan"
read_only_style = "red"
read_only = " ğŸ”’"
#show_symbol = "ï’‚ "
#home_symbol = "ï’‚ ~"
format = '[$path]($style)[$read_only]($read_only_style) '

# Replace the "â¯" symbol in the prompt with "â†³"
[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
#use_symbol_for_status = true

#[username]
#style_user = "bold yellow"
#style_root = "bold blue"
#format = "[$user]($style) @ "
#show_always = true

#[hostname]
#ssh_only = false                                                                                                                            
#format =  "[$hostname](bold white) in "                                                                                                     
#trim_at = ".companyname.com"                                                                                                                
#disabled = false

#The memory_usage module shows current system memory and swap usage
#[memory_usage]
#disabled = false
#threshold = -1
#symbol = "ğŸ’» "
#style = "bold yellow"
#format = "| $symbol[${ram}( | ${swap})]($style) "
